### ISSUE TITLE
Create Carousel for Home view

### ISSUE THREAD

**Issue by DevanBarger33** [DevanBarger33/aptitude-pt#20] opened 2017-10-01 22:43 UTC
Using the mockup, create a carousel as part of the home view.

**Comment by msClassE** [comment] 2017-10-16 22:58
Is this a duplicate of https://github.com/DevanBarger33/aptitude-pt/issues/3?

**Comment by DevanBarger33** [comment] 2017-10-17 02:44
Yeah this is a duplicate. The other one was one of my initial test issues. I don't know how I got two of them in here.

**Closed as completed** 2017-10-17 02:45 UTC
Labels: enhancement
